<a href="https://colab.research.google.com/github/np03cs4a240102-lang/Concepts-and-Technologies-of-AI/blob/main/Worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem - 1: Array Creation:


In [ ]:
import numpy as np
import time

print("\n================ PROBLEM 1: ARRAY CREATION ================\n")

# 1. Empty 2×2 array
empty_2x2 = np.empty((2,2))
print("1) Empty 2×2 array:\n", empty_2x2)

# 2. All–ones 4×2 array
ones_4x2 = np.ones((4,2))
print("\n2) Ones 4×2 array:\n", ones_4x2)

# 3. Full 3×3 array filled with a value
full_3x3 = np.full((3,3), 7)
print("\n3) Full 3×3 array filled with 7:\n", full_3x3)

# 4. Zeros like another array
sample = np.array([[2,3,4],[5,6,7]])
zeros_like_sample = np.zeros_like(sample)
print("\n4) Zeros like sample:\n", zeros_like_sample)

# 5. Ones like another array
ones_like_sample = np.ones_like(sample)
print("\n5) Ones like sample:\n", ones_like_sample)

# 6. Convert list to NumPy array
my_list = [1,2,3,4]
arr_from_list = np.array(my_list)
print("\n6) List converted to array:", arr_from_list)


================ PROBLEM 1: ARRAY CREATION ================

1) Empty 2×2 array:
 [[4.33891876e-315 0.00000000e+000]
 [2.89468780e-229 1.81320626e-287]]

2) Ones 4×2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3) Full 3×3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4) Zeros like sample:
 [[0 0 0]
 [0 0 0]]

5) Ones like sample:
 [[1 1 1]
 [1 1 1]]

6) List converted to array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1. Values from 10 to 49
arr_10_49 = np.arange(10,50)
print("2.1) Array 10 to 49:\n", arr_10_49)

# 2. 3×3 matrix from 0 to 8
mat_0_8 = np.arange(9).reshape(3,3)
print("\n2.2) Matrix 0 to 8:\n", mat_0_8)

# 3. Identity matrix 3×3
identity_3x3 = np.eye(3)
print("\n2.3) Identity 3×3:\n", identity_3x3)

# 4. Random array size 30 → mean
rand30 = np.random.random(30)
print("\n2.4) Mean of 30 random numbers:", rand30.mean())

# 5. Random 10×10 → min & max
rand10x10 = np.random.random((10,10))
print("\n2.5) Min:", rand10x10.min(), " Max:", rand10x10.max())

# 6. Replace 5th element with 1
zero10 = np.zeros(10)
zero10[4] = 1
print("\n2.6) Zero array with 5th element = 1:\n", zero10)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\n2.7) Reversed array:", arr[::-1])

# 8. 2D array border 1s, inside 0s
n = 5
border = np.ones((n,n))
border[1:-1, 1:-1] = 0
print("\n2.8) Border array (5×5):\n", border)

# 9. Checkerboard pattern 8×8
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n2.9) Checkerboard (8×8):\n", checker)

2.1) Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.2) Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2.3) Identity 3×3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

2.4) Mean of 30 random numbers: 0.5285235348417217

2.5) Min: 0.0005397320218459845  Max: 0.9964349508654158

2.6) Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

2.7) Reversed array: [0 4 0 0 2 1]

2.8) Border array (5×5):
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

2.9) Checkerboard (8×8):
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Matrix x:\n", x)
print("Matrix y:\n", y)

# 1. Addition
print("\n3.1) x + y:\n", x + y)

# 2. Subtraction
print("\n3.2) x - y:\n", x - y)

# 3. Multiply by integer
print("\n3.3) 3 * x:\n", 3 * x)

# 4. Square each element
print("\n3.4) x squared:\n", x**2)

# 5. Dot products
print("\n3.5) v · w =", v.dot(w))
print("x · v:\n", x.dot(v))
print("x · y:\n", x.dot(y))

# 6. Concatenate x and y row-wise
print("\n3.6) Concatenate x & y along rows:\n", np.concatenate((x,y), axis=0))

print("Concatenate v & w as columns:\n", np.column_stack((v,w)))

# 7. Concatenation error demonstration
print("\n3.7) Trying to concatenate x and v:")
try:
    np.concatenate((x, v), axis=0)
except Exception as e:
    print("Error:", e)
    print("Reason: shapes do not match.")

Matrix x:
 [[1 2]
 [3 5]]
Matrix y:
 [[5 6]
 [7 8]]

3.1) x + y:
 [[ 6  8]
 [10 13]]

3.2) x - y:
 [[-4 -4]
 [-4 -3]]

3.3) 3 * x:
 [[ 3  6]
 [ 9 15]]

3.4) x squared:
 [[ 1  4]
 [ 9 25]]

3.5) v · w = 219
x · v:
 [29 77]
x · y:
 [[19 22]
 [50 58]]

3.6) Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v & w as columns:
 [[ 9 11]
 [10 12]]

3.7) Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: shapes do not match.


Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
print("4.1) A * A^-1:\n", np.round(A.dot(A_inv), 8))

# 2. Show AB ≠ BA
print("\n4.2) AB:\n", A.dot(B))
print("BA:\n", B.dot(A))

# 3. (AB)^T = B^T A^T
print("\n4.3) (AB)^T:\n", (A.dot(B)).T)
print("     B^T A^T:\n", B.T.dot(A.T))

# 4. Solve system of equations
# 2x – 3y +  z = –1
#  x –  y + 2z = –3
# 3x +  y –  z =  9

coef = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

rhs = np.array([-1, -3, 9])

solution = np.linalg.solve(coef, rhs)
print("\n4.4) Solution of system:", solution)   # x=2, y=1, z=-2

4.1) A * A^-1:
 [[1. 0.]
 [0. 1.]]

4.2) AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

4.3) (AB)^T:
 [[23 51]
 [13 29]]
     B^T A^T:
 [[23 51]
 [13 29]]

4.4) Solution of system: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [ ]:
import numpy as np
import time

n = 1_000_000

# Python lists
list_a = list(range(n))
list_b = list(range(n, 2*n))

# 1. Element-wise addition
t0 = time.time()
list_add = [list_a[i] + list_b[i] for i in range(n)]
t1 = time.time()
print("List add time:", t1 - t0)

# NumPy arrays
na = np.arange(n)
nb = np.arange(n, 2*n)

t0 = time.time()
np_add = na + nb
t1 = time.time()
print("NumPy add time:", t1 - t0)

# 2. Element-wise multiplication
t0 = time.time()
list_mul = [list_a[i] * list_b[i] for i in range(n)]
t1 = time.time()
print("\nList multiply time:", t1 - t0)

t0 = time.time()
np_mul = na * nb
t1 = time.time()
print("NumPy multiply time:", t1 - t0)

# 3. Dot product
t0 = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(n))
t1 = time.time()
print("\nList dot time:", t1 - t0)

t0 = time.time()
dot_np = na.dot(nb)
t1 = time.time()
print("NumPy dot time:", t1 - t0)

print("\n================ END OF SOLUTIONS ================")


List add time: 0.22482728958129883
NumPy add time: 0.005570650100708008

List multiply time: 0.2362055778503418
NumPy multiply time: 0.005260467529296875

List dot time: 0.22954869270324707
NumPy dot time: 0.002550840377807617

================ END OF SOLUTIONS ================
